language: cpp
sudo: required
dist: trusty

os:
 - linux
 - osx

env:
 - BUILD_MODE=release
 - BUILD_MODE=debug

install:
 - |
   if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
     export MKSPEC=linux-g++
     sudo apt-get install -y debhelper qt5-default libqt5widgets5 libhidapi-dev libusb-1.0-0-dev fakeroot
   fi
 - |
   if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
     export MKSPEC=macx-clang
     brew install pkg-config qt hidapi libusb
     brew link qt --force
   fi

script:
 - echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
 - mkdir build
 - cd build
 - qmake ../hv-ms735-config.pro -spec ${MKSPEC} CONFIG+=${BUILD_MODE}
 - make


branches:
  only:
    - master
