language: c++
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -y debhelper qt5-default libqt5widgets5 libhidapi-dev libusb-1.0-0-dev fakeroot
script:
  - dpkg-buildpackage -us -uc -I.git -rfakeroot


