version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2013

environment:
  QT_DIR: C:\Qt\5.8\mingw53_32
  MINGW_DIR: C:\Qt\Tools\mingw530_32

# Fix line endings on Windows
init:
- git config --global core.autocrlf true

install:
- set PATH=%MINGW_DIR%\bin;%QT_DIR%\bin;c:\msys64\mingw32\bin;%PATH%

build_script:
- qmake
- mingw32-make

artifacts:
- path: Release\*.exe
  name: windows-executable
