version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2013

environment:
  QT_DIR: C:\Qt\5.8\mingw53_32
  MINGW_DIR: C:\Qt\Tools\mingw530_32

configuration:
  - Release

# Fix line endings on Windows
init:
- git config --global core.autocrlf true

install:
- set PATH=%MINGW_DIR%\bin;%QT_DIR%\bin;c:\msys64\mingw32\bin;%WIX%\bin;%PATH%

build_script:
- qmake
- mingw32-make -f Makefile.$(configuration)
- windeployqt.exe --no-svg --no-angle --no-opengl-sw --no-system-d3d-compiler --no-translations --libdir qtredist --plugindir qtredist $(configuration)\hv-ms735-config.exe
- heat dir qtredist -cg CG_QtRedist -ag -srd -sfrag -dr INSTALLDIR -out qtredist.wxs
- candle -dConfiguration=$(configuration) -dLibDir=qtredist hv-ms735-config.wxs qtredist.wxs
- light hv-ms735-config.wixobj qtredist.wixobj -out $(configuration)\hv-ms735-config.msi

artifacts:
- path: $(configuration)\hv-ms735-config.msi
  name: windows-installer
